// Package seed embeds the prebuilt offline food database. The bytes are a
// gzipped SQLite database generated by the ETL tool (`make etl`, tools/etl)
// from USDA FoodData Central SR Legacy data.
package seed

import _ "embed"

//go:embed foods.sqlite.gz
var gzipped []byte

// Gzip returns the embedded gzipped SQLite seed database. It is empty only if
// the project is built without first running the ETL to generate the asset.
func Gzip() []byte { return gzipped }
